jaffle_shop:
  outputs:
    dev:
      dataset: DW
      job_execution_timeout_seconds: 300
      job_retries: 1
      location: US
      method: oauth
      priority: interactive
      project: dwh-adev-ae-intro
      threads: 1
      type: bigquery
  target: dev
  